buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        def agpVersion = findProperty('agpVersion') ?: '8.5.2'
        def kotlinVersion = findProperty('kotlinVersion') ?: '1.9.24'
        classpath "com.android.tools.build:gradle:${agpVersion}"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}"
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
